print(" program that computes the value of a+aa+aaa+aaaa with a given digit as the value of a")
print("------------------------------------------------------------")
a=input("Enter the string")
n1=int("%s"%a)
n2=int("%s%s"%(a,a))
n3=int("%s%s%s"%(a,a,a))
n4=int("%s%s%s%s"%(a,a,a,a))
print(n1+n2+n3+n4)
